version: '3.7'
services:
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - "27017:27017"
  unicorn-app:
    image: unicorn-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8087:8080'
    volumes:
      - /data/unicorn-app
    depends_on:
      - mongo_db